version: '2'

services:
  server:
    build: .
    ports:
      - '8080:8080'
      - '6000:6000'
    environment:
      - REDIS_URL=redis
      - ALLOW_ACCOUNT_CREATION=true
    depends_on:
      - redis
    volumes:
      - ./app:/opt/server/repo_app
    networks:
      default:
      internal:

  redis:
    image: 'bitnami/redis:5.0'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    networks:
      internal:

volumes:
  redis_data:
    driver: local

networks:
    default:
    internal:
        internal: true
